version: '3.9'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
    networks:
      - elk_network
  logstash:
    image: docker.io/bitnami/logstash:8
    ports:
      - '8080:8080'
    volumes:
      - 'logstash_data:/bitnami'
    networks:
      - elk_network
  kibana:
    image: docker.io/bitnami/kibana:8
    ports:
      - '5601:5601'
    volumes:
      - 'kibana_data:/bitnami/kibana'
    depends_on:
      - elasticsearch
    networks:
      - elk_network
volumes:
  elasticsearch_data:
    driver: local
  kibana_data:
    driver: local
  logstash_data:
    driver: local
networks:
  elk_network:
    driver: bridge